// Academic-page text, synchronized with academic_cv_template.tex on 2026-10-07.
// Keep submission statuses and redacted project names as provided in the CV.
window.pageTranslations = {
  zh: {
    description: "韩咏烜，上海交通大学计算机科学专业在读博士生，研究无人机三维重建与端云协同多媒体处理。",
    degree: "计算机科学专业 · 博士研究生", phoneLabel: "电话",
    workTitle: "实习 / 工作经历", skillsTitle: "技术能力", projectsTitle: "项目经历", publicationsTitle: "论文",
    personalFootnote: "个人生活页", underConstruction: "页面施工中",
    phdDates: "2023.09 — 至今", phdDetails: "计算机科学专业 · 博士在读", advisor: "导师：刘生钟",
    mastersUniversity: "University of Birmingham", mastersDetails: "MSc in Data Science（with Distinction）",
    bachelorsUniversity: "北京理工大学", bachelorsDetails: "机械电子工程 · 本科（全英文教学班）",
    employer: "万物云空间科技服务股份有限公司", internshipRole: "算法实习生 · 深圳",
    internshipOne: "负责内部数据标注平台的开发与测试，开展图像处理算法的功能验证。",
    internshipTwo: "集成语义分割算法，优化远程访问场景下的预标注性能。",
    researchUavTitle: "无人机三维重建", researchUavBody: "面向城市级场景的实时三维建模与空地协同重建。",
    researchEdgeTitle: "端云协同多媒体处理", researchEdgeBody: "面向下游任务需求的端云协同实时图像处理。",
    indoorTitle: "全景相机室内三维建模", indoorDates: "2026.04 — 至今",
    indoorRole: "中国建筑一局 · 主导前期技术验证与项目实施",
    indoorGoal: "基于双目全景相机，实现室内场景的高保真三维建模。",
    indoorMethod: "无需 ERP 投影即可进行高保真场景重建，自动遮罩与场景无关的信息。",
    uavTitle: "无人机实时三维建模", uavDates: "2015.12 — 2026.06",
    uavRole: "上海红鹅网络信息技术有限公司 · 主导项目实施与技术开发",
    uavGoal: "实现无人机数据采集与三维建模同步进行。",
    uavMethod: "基于内容的实时关键帧自动筛选，与数据收集同步并行分区进行 3DGS 重建。",
    demoLabel: "项目演示",
    adaptiveTitle: "XXXX地面时敏目标多源XX敏捷处理技术", adaptiveDates: "2025.03 — 至今",
    adaptiveRole: "军科委项目 · 前期技术验证",
    adaptiveTask: "负责子课题：网络自适应三维 XX 地图构建与目标定位；设备自适应的端侧模型压缩与部署优化。",
    adaptiveResultOne: "实现由粗到细的两阶段实时三维地图重建。",
    adaptiveResultTwo: "在计算资源受限条件下完成端侧模型部署，并保持任务精度。",
    fusionTitle: "面向XXX的多源XX目标指示信息智能生成算法",
    fusionRole: "军科委项目 · 主导项目技术开发",
    fusionProblem: "多源图像异构性强，目标信息的融合与判定困难。",
    fusionMethod: "利用多头自注意力机制，自适应融合可见光、近红外与 SAR 图像特征。",
    fusionResult: "多源融合目标指示信息生成精度提升 12%，生成时延降低 56%。",
    submitted: "在投", oralPresentation: "受邀进行口头报告",
    patentsTitle: "专利", patentTitle: "基于SAM模型的图像标注方法、装置及相关介质",
    patentLabel: "专利号", patentAuthorsPrefix: "发明人：周长源、", patentSelf: "韩咏烜",
    programmingLabel: "编程语言", programmingBody: "熟练使用 Python，较熟悉 C/C++。",
    droneLabel: "无人机", droneBody: "具备 CAAC 中型无人机超视距驾驶资质，熟悉大疆 Matrice 系列软硬件开发。",
    systemsLabel: "服务器运维", systemsBody: "熟悉 Debian 系 Linux 系统运维及各类服务器硬件检修维护。",
    languageLabel: "语言能力", languageBody: "雅思（IELTS）总分 8.0。"
  },
  en: {
    description: "Yongxuan Han is a PhD student in computer science at Shanghai Jiao Tong University, researching UAV 3D reconstruction and edge–cloud collaborative multimedia processing.",
    degree: "PhD Student · Computer Science", phoneLabel: "Phone",
    workTitle: "Work Experience", skillsTitle: "Technical Skills", projectsTitle: "Projects", publicationsTitle: "Publications",
    personalFootnote: "Personal Life", underConstruction: "Page under construction",
    phdDates: "2023.09 — Present", phdDetails: "PhD in Computer Science · In progress", advisor: "Advisor: Shengzhong Liu",
    mastersUniversity: "University of Birmingham", mastersDetails: "MSc in Data Science, with Distinction",
    bachelorsUniversity: "Beijing Institute of Technology", bachelorsDetails: "Bachelor’s degree in Mechatronics Engineering · English-taught program",
    employer: "万物云空间科技服务股份有限公司", internshipRole: "Algorithm Intern · Shenzhen",
    internshipOne: "Developed and tested an internal data annotation platform and validated image processing algorithms.",
    internshipTwo: "Integrated semantic segmentation algorithms to improve pre-annotation performance in remote-access scenarios.",
    researchUavTitle: "UAV 3D Reconstruction", researchUavBody: "Real-time city-scale 3D modeling and collaborative aerial–ground reconstruction.",
    researchEdgeTitle: "Edge–Cloud Collaborative Multimedia Processing", researchEdgeBody: "Real-time image processing across edge devices and the cloud, tailored to downstream tasks.",
    indoorTitle: "Indoor 3D Modeling with Panoramic Cameras", indoorDates: "2026.04 — Present",
    indoorRole: "中国建筑一局 · Led preliminary technical validation and project implementation",
    indoorGoal: "High-fidelity indoor 3D modeling using a stereo panoramic camera.",
    indoorMethod: "Validated high-fidelity scene reconstruction without ERP projection, with automatic masking of scene-irrelevant content.",
    uavTitle: "Real-Time UAV 3D Modeling", uavDates: "2015.12 — 2026.06",
    uavRole: "上海红鹅网络信息技术有限公司 · Led project implementation and technical development",
    uavGoal: "Concurrent UAV data acquisition and 3D modeling.",
    uavMethod: "Real-time content-based keyframe selection and parallel block-wise 3D Gaussian Splatting reconstruction concurrent with data collection.",
    demoLabel: "Project demo",
    adaptiveTitle: "XXXX Multi-source XX Agile Processing for Ground Time-Sensitive Targets", adaptiveDates: "2025.03 — Present",
    adaptiveRole: "Military Science and Technology Commission project · Preliminary technical validation",
    adaptiveTask: "Subprojects: network-adaptive 3D XX map construction and target localization; device-adaptive model compression and edge deployment optimization.",
    adaptiveResultOne: "Implemented coarse-to-fine, two-stage real-time 3D map reconstruction.",
    adaptiveResultTwo: "Deployed models on resource-constrained edge devices while maintaining task accuracy.",
    fusionTitle: "Intelligent Generation of Multi-source XX Target Indication Information for XXX",
    fusionRole: "Military Science and Technology Commission project · Led technical development",
    fusionProblem: "Addressed the difficulty of fusing and interpreting target information from highly heterogeneous multi-source imagery.",
    fusionMethod: "Used multi-head self-attention to adaptively fuse visible-light, near-infrared, and SAR image features.",
    fusionResult: "Improved the accuracy of multi-source target indication information generation by 12% and reduced generation latency by 56%.",
    submitted: "Under review", oralPresentation: "Invited oral presentation",
    patentsTitle: "Patents", patentTitle: "SAM-Based Image Annotation Method, Apparatus, and Related Media",
    patentLabel: "Patent", patentAuthorsPrefix: "Inventors: Changyuan Zhou; ", patentSelf: "Yongxuan Han",
    programmingLabel: "Programming", programmingBody: "Proficient in Python; familiar with C/C++.",
    droneLabel: "UAV Systems", droneBody: "CAAC qualification for beyond-visual-line-of-sight operation of medium-sized UAVs; familiar with DJI Matrice-series software and hardware development.",
    systemsLabel: "Systems Administration", systemsBody: "Experience with Debian-based Linux administration and server hardware troubleshooting and maintenance.",
    languageLabel: "Languages", languageBody: "IELTS overall band score: 8.0."
  }
};
